# Learning Numpy


In [1]:
import numpy as np

In [97]:
myArr = np.array([[1,23,45,21]], dtype=np.int8) # 2d array and also can set datatype -> int8 => means 8 bits (small) integer

In [99]:
myArr.dtype

dtype('int8')

In [4]:
type(myArr)

numpy.ndarray

In [5]:
myArr.ndim

2

In [6]:
myArr[0,2] # 1st row 3rd col element access element of 2d array or matrix

45

In [7]:
myArr.dtype

dtype('int64')

## Matrix (2-D Array)

In [10]:
A = np.array([
    [3,2,5],
    [4,6,1],
    [7,9,3]
])

In [12]:
A

array([[3, 2, 5],
       [4, 6, 1],
       [7, 9, 3]])

In [13]:
A.shape

(3, 3)

In [14]:
A.ndim

2

### Matrix Slicing

In [15]:
A[2,1] # access element from 2-D array

9

In [16]:
A[0:2] # row -> 0 and 1 col full

array([[3, 2, 5],
       [4, 6, 1]])

In [17]:
A[0:2,0:1] # row -> 0 and 1 but col only 0

array([[3],
       [4]])

In [20]:
A.transpose()

array([[3, 4, 7],
       [2, 6, 9],
       [5, 1, 3]])

In [21]:
A

array([[3, 2, 5],
       [4, 6, 1],
       [7, 9, 3]])

In [23]:
A.trace()

12

## Axis System

In [24]:
a = np.array([12,34,11,67])

In [25]:
a

array([12, 34, 11, 67])

In [29]:
a.sum() # for 1-D array only 1 axis -> axis=0 (row or horizontal)

124

In [30]:
A

array([[3, 2, 5],
       [4, 6, 1],
       [7, 9, 3]])

In [31]:
A.sum() # sum of all element horizontal axis (Axis =1 ) 

40

In [32]:
A.sum(axis=0) # for non 1-D array axis=0 => col (vertical) and axis=1 => row (horizontal)

array([14, 17,  9])

In [33]:
A.sum(axis=1)

array([10, 11, 19])

### Broadcasting and Vectorized operations

In [34]:
a

array([12, 34, 11, 67])

In [35]:
a + 2 # Add 2 with all of elem

array([14, 36, 13, 69])

In [36]:
A

array([[3, 2, 5],
       [4, 6, 1],
       [7, 9, 3]])

In [37]:
A * 3

array([[ 9,  6, 15],
       [12, 18,  3],
       [21, 27,  9]])

In [43]:
a = np.arange(5) # arrange -> range in normal python

In [44]:
a

array([0, 1, 2, 3, 4])

## Bolean Operation

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a >= 2

array([False, False,  True,  True,  True])

In [95]:
a[a>=2] # which elem satisfy the condition 

array([2, 3, 4])

In [94]:
import random

In [80]:
A = np.random.randint(100, size=(3, 3)) # generate a random numpy array whose range -> 0 to 100

In [90]:
A

array([[49, 44, 76],
       [75, 87, 32],
       [96, 64, 84]])

In [79]:
random.randint(0,100)

61

In [91]:
A.dtype

dtype('int64')